// Supabase未接続時のフォールバック用モックデータ。
// 実在の人物・作品を示唆しないよう、女優名には「架空」を冠した明確な仮名を使う。
import type {
  Actress,
  Alias,
  DistributionPlatform,
  Genre,
  Label,
  Maker,
  Series,
  UsedMarketPlatform,
  Work,
  WorkActress,
  WorkDistributionLink,
  WorkGenre,
  WorkMarketPrice,
  WorkRarityNote,
} from "@/types/database";

export const mockMakers: Maker[] = [
  { id: "maker-1", slug: "studio-a", name: "Studio A", description: "サンプルメーカーA。", created_at: "2020-01-01T00:00:00Z" },
  { id: "maker-2", slug: "studio-b", name: "Studio B", description: "サンプルメーカーB。", created_at: "2020-01-01T00:00:00Z" },
];

export const mockLabels: Label[] = [
  {
    id: "label-1",
    maker_id: "maker-1",
    slug: "label-prime",
    name: "Label Prime",
    description: "Studio A配下のレーベル。",
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2020-01-01T00:00:00Z",
  },
  {
    id: "label-2",
    maker_id: "maker-2",
    slug: "label-next",
    name: "Label Next",
    description: "Studio B配下のレーベル。",
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2020-01-01T00:00:00Z",
  },
];

export const mockSeries: Series[] = [
  {
    id: "series-1",
    maker_id: "maker-1",
    label_id: "label-1",
    slug: "classic-collection",
    name: "Classic Collection",
    description: "Label Primeの代表シリーズ。",
    created_at: "2020-01-01T00:00:00Z",
  },
  {
    id: "series-2",
    maker_id: "maker-2",
    label_id: "label-2",
    slug: "new-wave",
    name: "New Wave",
    description: "Label Nextの新作シリーズ。",
    created_at: "2020-01-01T00:00:00Z",
  },
];

export const mockGenres: Genre[] = [
  { id: "genre-1", slug: "single", name: "単体作品", description: null, created_at: "2020-01-01T00:00:00Z" },
  { id: "genre-2", slug: "best", name: "総集編", description: null, created_at: "2020-01-01T00:00:00Z" },
  { id: "genre-3", slug: "drama", name: "ドラマ", description: null, created_at: "2020-01-01T00:00:00Z" },
];

export const mockActresses: Actress[] = [
  {
    id: "actress-1",
    slug: "kako-hanako",
    name: "架空 花子",
    kana: "かくう はなこ",
    profile: "サンプルデータ用の仮名女優。",
    thumbnail_url: null,
    thumbnail_license: null,
    works_count: 2,
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2020-01-01T00:00:00Z",
  },
  {
    id: "actress-2",
    slug: "kako-sakura",
    name: "架空 桜",
    kana: "かくう さくら",
    profile: "サンプルデータ用の仮名女優。",
    thumbnail_url: null,
    thumbnail_license: null,
    works_count: 1,
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2020-01-01T00:00:00Z",
  },
];

// 公式発表済みの旧芸名のみを保存する設計例（本人/事務所発表を想定したダミー）。
export const mockAliases: Alias[] = [
  {
    id: "alias-1",
    actress_id: "actress-1",
    name: "架空 華",
    kana: "かくう はな",
    alias_type: "former_stage_name",
    source_type: "official_agency",
    source_url: "https://example.com/official-announcement",
    valid_from: "2018-01-01",
    valid_to: "2019-12-31",
    note: "所属事務所公式発表による旧芸名。",
    created_at: "2020-01-01T00:00:00Z",
  },
];

export const mockWorks: Work[] = [
  {
    id: "work-1",
    slug: "aaa-001",
    title: "Classic Collection Vol.1",
    product_code: "AAA-001",
    maker_id: "maker-1",
    label_id: "label-1",
    series_id: "series-1",
    release_date: "2012-04-01",
    runtime_minutes: 110,
    permitted_thumbnail_url: null,
    thumbnail_license: null,
    seo_description: "廃盤・希少タイトルのサンプル作品。",
    favorite_count: 42,
    view_count: 1280,
    rating_avg: 4.5,
    rating_count: 2,
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2020-01-01T00:00:00Z",
  },
  {
    id: "work-2",
    slug: "aaa-002",
    title: "Classic Collection Vol.2",
    product_code: "AAA-002",
    maker_id: "maker-1",
    label_id: "label-1",
    series_id: "series-1",
    release_date: "2013-06-15",
    runtime_minutes: 115,
    permitted_thumbnail_url: null,
    thumbnail_license: null,
    seo_description: "シリーズ第2弾のサンプル作品。",
    favorite_count: 18,
    view_count: 640,
    rating_avg: null,
    rating_count: 0,
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2020-01-01T00:00:00Z",
  },
  {
    id: "work-3",
    slug: "bbb-101",
    title: "New Wave Debut",
    product_code: "BBB-101",
    maker_id: "maker-2",
    label_id: "label-2",
    series_id: "series-2",
    release_date: "2026-03-01",
    runtime_minutes: 120,
    permitted_thumbnail_url: null,
    thumbnail_license: null,
    seo_description: "最新作のサンプル作品。",
    favorite_count: 5,
    view_count: 210,
    rating_avg: null,
    rating_count: 0,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "work-4",
    slug: "bbb-102",
    title: "New Wave Second",
    product_code: "BBB-102",
    maker_id: "maker-2",
    label_id: "label-2",
    series_id: "series-2",
    release_date: "2026-05-01",
    runtime_minutes: 118,
    permitted_thumbnail_url: null,
    thumbnail_license: null,
    seo_description: null,
    favorite_count: 2,
    view_count: 95,
    rating_avg: null,
    rating_count: 0,
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-05-01T00:00:00Z",
  },
];

// 公式クレジットのみ。第三者による出演者補完は行わない。
export const mockWorkActress: WorkActress[] = [
  { work_id: "work-1", actress_id: "actress-1", billing_order: 0, credit_name: "架空 花子", source_type: "official_metadata", created_at: "2020-01-01T00:00:00Z" },
  { work_id: "work-2", actress_id: "actress-1", billing_order: 0, credit_name: "架空 花子", source_type: "official_metadata", created_at: "2020-01-01T00:00:00Z" },
  { work_id: "work-3", actress_id: "actress-2", billing_order: 0, credit_name: "架空 桜", source_type: "official_metadata", created_at: "2026-03-01T00:00:00Z" },
  // work-4は意図的に出演者未クレジット（OfficialInfoNoticeの表示確認用）。
];

export const mockWorkGenres: WorkGenre[] = [
  { work_id: "work-1", genre_id: "genre-1" },
  { work_id: "work-2", genre_id: "genre-1" },
  { work_id: "work-2", genre_id: "genre-2" },
  { work_id: "work-3", genre_id: "genre-1" },
  { work_id: "work-3", genre_id: "genre-3" },
  { work_id: "work-4", genre_id: "genre-1" },
];

export const mockDistributionPlatforms: DistributionPlatform[] = [
  {
    id: "platform-fanza-dmm",
    slug: "fanza-dmm",
    name: "FANZA / DMM",
    operator_name: "DMM",
    platform_type: "vod_store",
    website_url: "https://www.dmm.co.jp/digital/videoa/",
    affiliate_signup_url: null,
    country_code: "JP",
    priority: 10,
    is_adult: true,
    legal_review_status: "pending",
    status: "active",
    notes: null,
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2020-01-01T00:00:00Z",
  },
  {
    id: "platform-sod",
    slug: "sod",
    name: "SOD / SOD Prime / SOD Store",
    operator_name: "SOD",
    platform_type: "maker_official",
    website_url: "https://ec.sod.co.jp/",
    affiliate_signup_url: null,
    country_code: "JP",
    priority: 20,
    is_adult: true,
    legal_review_status: "pending",
    status: "active",
    notes: null,
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2020-01-01T00:00:00Z",
  },
  {
    id: "platform-mgstage",
    slug: "mgstage",
    name: "MGS動画",
    operator_name: "MGS",
    platform_type: "vod_store",
    website_url: "https://www.mgstage.com/",
    affiliate_signup_url: null,
    country_code: "JP",
    priority: 30,
    is_adult: true,
    legal_review_status: "pending",
    status: "active",
    notes: null,
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2020-01-01T00:00:00Z",
  },
];

export const mockWorkDistributionLinks: WorkDistributionLink[] = [
  {
    id: "wdl-1",
    work_id: "work-1",
    platform_id: "platform-fanza-dmm",
    affiliate_link_id: null,
    platform_product_code: "AAA-001",
    platform_work_url: "https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=aaa001/",
    availability_status: "unavailable",
    offer_type: "unknown",
    intent_type: "official_reference",
    cta_priority: 10,
    region_note: null,
    price_note: "配信終了（廃盤）",
    checked_at: "2026-06-01T00:00:00Z",
    created_at: "2020-01-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "wdl-2",
    work_id: "work-3",
    platform_id: "platform-fanza-dmm",
    affiliate_link_id: null,
    platform_product_code: "BBB-101",
    platform_work_url: "https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=bbb101/",
    availability_status: "available",
    offer_type: "purchase",
    intent_type: "ppv_primary",
    cta_priority: 10,
    region_note: null,
    price_note: "単品購入 2,980円〜（参考）",
    checked_at: "2026-07-01T00:00:00Z",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-07-01T00:00:00Z",
  },
  {
    id: "wdl-3",
    work_id: "work-3",
    platform_id: "platform-sod",
    affiliate_link_id: null,
    platform_product_code: "BBB-101",
    platform_work_url: "https://ec.sod.co.jp/prime/videos/?id=bbb101",
    availability_status: "available",
    offer_type: "subscription",
    intent_type: "subscription_secondary",
    cta_priority: 50,
    region_note: null,
    price_note: "見放題プラン対象（参考）",
    checked_at: "2026-07-01T00:00:00Z",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-07-01T00:00:00Z",
  },
];

// 第二の収益核: 中古相場サンプル（docs/used-market-pricing.md）。
export const mockUsedMarketPlatforms: UsedMarketPlatform[] = [
  { id: "used-mercari", slug: "mercari", name: "メルカリ", platform_type: "c2c_marketplace", website_url: "https://jp.mercari.com/", data_source_type: "affiliate_feed", status: "active", created_at: "2020-01-01T00:00:00Z", updated_at: "2020-01-01T00:00:00Z" },
  { id: "used-yahoo-auction", slug: "yahoo-auction", name: "ヤフオク!", platform_type: "auction", website_url: "https://auctions.yahoo.co.jp/", data_source_type: "affiliate_feed", status: "active", created_at: "2020-01-01T00:00:00Z", updated_at: "2020-01-01T00:00:00Z" },
  { id: "used-surugaya", slug: "surugaya", name: "駿河屋", platform_type: "secondhand_store", website_url: "https://www.suruga-ya.jp/", data_source_type: "affiliate_feed", status: "active", created_at: "2020-01-01T00:00:00Z", updated_at: "2020-01-01T00:00:00Z" },
];

export const mockWorkMarketPrices: WorkMarketPrice[] = [
  {
    id: "price-1",
    work_id: "work-1",
    platform_id: "used-mercari",
    price_type: "current_listing_avg",
    price_yen: 8800,
    sample_size: 6,
    observed_at: "2026-07-01T00:00:00Z",
    source_url: "https://jp.mercari.com/search?keyword=AAA-001",
    affiliate_link_id: null,
    created_at: "2026-07-01T00:00:00Z",
  },
  {
    id: "price-2",
    work_id: "work-1",
    platform_id: "used-yahoo-auction",
    price_type: "completed_sale_avg",
    price_yen: 11200,
    sample_size: 4,
    observed_at: "2026-07-01T00:00:00Z",
    source_url: "https://auctions.yahoo.co.jp/search/search?p=AAA-001",
    affiliate_link_id: null,
    created_at: "2026-07-01T00:00:00Z",
  },
  {
    id: "price-3",
    work_id: "work-1",
    platform_id: "used-surugaya",
    price_type: "current_listing_min",
    price_yen: 7500,
    sample_size: 2,
    observed_at: "2026-07-01T00:00:00Z",
    source_url: "https://www.suruga-ya.jp/search?category=&search_word=AAA-001",
    affiliate_link_id: null,
    created_at: "2026-07-01T00:00:00Z",
  },
];

export const mockWorkRarityNotes: WorkRarityNote[] = [
  {
    id: "rarity-1",
    work_id: "work-1",
    rarity_reason: "out_of_print",
    note: "発売元より販売終了が発表されている（サンプルデータ）。",
    source_url: "https://example.com/label-discontinued-notice",
    created_at: "2026-06-01T00:00:00Z",
  },
];
